name: Build and deploy ASP.Net Core app on AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-image-with-docker:
    name: Build API To Docker Image And Push To DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3

      - name: DockerHub Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build Image And Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          no-cache: true
          tags: ${{secrets.DOCKER_USERNAME}}/tutor-link-api:latest
          
  staging-webapp-deploy:
    name: Deploy Web Api To Server For Testing
    runs-on: tin-truong-aws
    needs: build-image-with-docker
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    steps:
    - name: Checkout Develop
      uses: actions/checkout@v3
    - name: DockerHub Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Stop API
      run: docker compose -p tutor-link-test down tutor-link-api
      continue-on-error: true
    - name: Clean Old Image
      run: docker rmi ${{secrets.DOCKER_USERNAME}}/tutor-link-api:latest 
      continue-on-error: true
    - name: Deploy API
      run: docker compose -p tutor-link-test up -d
